### ISSUE TITLE
Support uncommon debit cards

### ISSUE THREAD

**Issue by bendrucker** [bendrucker/creditcards-types#1]
jquery.payments supports a pretty broad range of foreign cards: 

https://github.com/stripe/jquery.payment/blob/c5e895412c45553bc6d6d22f32faae2288233440/src/jquery.payment.coffee#L13-L44

This'll require some doing because it means exposing an interface for how lookups should be prioritized instead of just looping the properties

**Comment by bendrucker** [comment]
Todo:

[ ] Forbrugsforeningen
[ ] Dankort
[ ] Visa Electron

**Comment by lookfirst** [comment]
Any reason why you didn't finish your todo list and closed the issue?

**Comment by bendrucker** [comment]
Visa Electron is the only card type that has total overlap with another card type (Visa). That means offering an API for iterating through cards in a specified order. I haven't had time to think enough about the best way to implement that.
