### ISSUE TITLE
 False-positive "invalid ccNumber" when using a valid number

### ISSUE THREAD

**Issue by gustavoramos00** [bendrucker/creditcards-types#10]
The following numbers are valid credit card numbers, but an error occurs when using them:
6362970000457013 (Elo)
6062825624254001 (HiperCard)
5078601912345600019 (Aura)

You can check the numbers in this sites:
http://www.validcreditcardnumber.com/
http://www.freeformatter.com/credit-card-number-generator-validator.html

Thanks

**Comment by bendrucker** [comment]
See #3. I'm okay keeping this open but I don't want to promise anything because every time supporting these card types has come up no one ever has any info.

**Comment by gustavoramos00** [comment]
Thanks for your attention. The problem for me isn't identify the card type, but fire an "invalid card number". For example, this Aura card 5078601912345600019 isn't identified, but is considered valid by this api.

**Comment by bendrucker** [comment]
Yeah basically the setup is that a card has to match a type otherwise it's considered invalid

**Comment by gustavoramos00** [comment]
I get it... I'm using the angular version, so i'm talking about it:

With a valid card number that has a type that is not yet identified by this library, the error on the number form field seems like this:
"$error":{"ccNumber":true,"ccNumberType":true}

In my opinion the error occurs only in ccNumberType. The ccNumber should be ok since it's a valid number against the luhn algorithm.

**Comment by bendrucker** [comment]
Closing, I'll only commit to supporting those card types if someone can help me get docs.
