### ISSUE TITLE
MasterCard type check does not have new BIN range

### ISSUE THREAD

**Issue by dlabey** [bendrucker/creditcards-types#11]
Just putting this here as by October 2016 there will be a new MasterCard BIN type implemented. The range is going to be 222100-272099.

**Comment by bendrucker** [comment]
Awesome, thanks for the heads up! Do you have a link to the doc where you read this by any chance?

**Comment by dlabey** [comment]
We were notified by our merchant processor. But here is an article: https://www.forte.net/blog/mastercard-bin-range-coming/

**Comment by bendrucker** [comment]
Figured it couldn't hurt to support it early
