### ISSUE TITLE
Discover test numbers matching as Maestro cards

### ISSUE THREAD

**Issue by matt-zangen** [bendrucker/creditcards-types#13]
A common example of a Discover card number used in testing is 6011111111111117 as can be seen on a few major card processor docs:

https://stripe.com/docs/testing#cards
https://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm

A regex test of the Discover type's pattern and eager pattern do not match for this number:

Eager: https://regex101.com/r/aH5jP1/1
Pattern: https://regex101.com/r/zW5oM2/1

These numbers do match on the Maestro type, however:

Eager: https://regex101.com/r/mN1qO2/1
Pattern: https://regex101.com/r/rJ9lD8/1

The other test number listed, 6011000990139424 , does match as Discover and not Maestro.

I'm not sure if it's the number that is incorrect, or the pattern, but this got flagged by QA since the first test number failed validation when excluding the Maestro type.

My workaround was to allow the Maestro type, but display the type as Discover via icon. Not ideal since it lacks Discover formatting, and when it's actually a Maestro card will be accepted by the front-end only to be rejected by the payment processor, but it works in the meantime.

I'm using angular-credit-cards, but it seems unrelated.

**Comment by mitchwinn** [comment]
I have the same exact problem as well. The only way around it for me was to change the regex.

**Comment by bendrucker** [comment]
It's a mystery to me why Stripe et al chose that one invalid card number (the one in question) and one valid (the second one).  It's very explicitly [not in Discover's documented range](https://www.discovernetwork.com/merchants/images/Merchant_Marketing.pdf) and does fall in the [Maestro docs](https://www.barclaycard.co.uk/business/files/Ranges-and-Rules-February-2016.pdf). Maestro occupies pretty much the whole 5/6 ranges, at least docs wise, with specific exclusions for MasterCard and Discover ranges.

In reality I don't think anyone actually issues in that specific range. Nevertheless, I've chosen to keep the creditcards-types validators tightly linked to available range docs.

**Comment by yuxiaomin** [comment]
@bendrucker I also ran into the same issue. The links you provided as proof in previous comment are no longer there.

**Comment by paveleremin** [comment]
@mitchwinn could you please provide a solution?
