### ISSUE TITLE
Maestro

### ISSUE THREAD

**Issue by benfoster** [bendrucker/creditcards-types#2]
Do you know if/when Maestro card matching may get added? Currently being matched as a Discover card.

**Comment by bendrucker** [comment]
There's some overlap with #1 here but it seems like Maestro poses the biggest issue so I'll keep this open for Maestro-specific discussion. Discover actually maintains a much narrower range and so prioritizing the debit cards in lookups should work. I've got a bunch of stuff to work on this weekend with credit cards, specifically this and supporting formatting/masking.

http://en.wikipedia.org/wiki/Bank_card_number#Issuer_identification_number_.28IIN.29

**Comment by bendrucker** [comment]
This is now released and will require a minor version update in any downstream packages (creditcards, angular-credit-cards)

**Comment by benfoster** [comment]
Thanks for that Ben.

Perhaps I'm mistaken but I could have sworn installing angular-credit-cards
pulled in creditcards automatically before. However, I just checked
bower.json and creditcards isn't listed as a dependency.

On 30 March 2015 at 17:26, Ben Drucker <notifications@github.com> wrote:

> This is now released and will require a minor version update in any
> downstream packages (creditcards, angular-credit-cards)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bendrucker/creditcards-types/issues/2#issuecomment-87742062>
> .
>



-- 

Ben Foster
planetcloud

*fabrik.*
The portfolio and blogging service for creatives.
info@getfabrik.com
http://getfabrik.com

**Comment by benfoster** [comment]
Also, it looks like this is no longer matching Maestro cards. I'm testing
with the number 6759000000000000.

On 30 March 2015 at 23:22, Ben Foster <ben@planetcloud.co.uk> wrote:

> Thanks for that Ben.
>
> Perhaps I'm mistaken but I could have sworn installing
> angular-credit-cards pulled in creditcards automatically before. However, I
> just checked bower.json and creditcards isn't listed as a dependency.
>
> On 30 March 2015 at 17:26, Ben Drucker <notifications@github.com> wrote:
>
>> This is now released and will require a minor version update in any
>> downstream packages (creditcards, angular-credit-cards)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bendrucker/creditcards-types/issues/2#issuecomment-87742062>
>> .
>>
>
>
>
> --
>
> Ben Foster
> planetcloud
>
> *fabrik.*
> The portfolio and blogging service for creatives.
> info@getfabrik.com
> http://getfabrik.com
>
>


-- 

Ben Foster
planetcloud

*fabrik.*
The portfolio and blogging service for creatives.
info@getfabrik.com
http://getfabrik.com

**Comment by bendrucker** [comment]
It's not a dependency because it's inlined when doing the UMD build. I keep `bower.json` files strictly to point `main` to the build file. And as with any time Bower comes up, here's my pitch for npm: https://github.com/bendrucker/discuss/issues/1#issuecomment-70028892

I screwed up the UMD build for 2.2.0 by forgetting to update deps before building for the tag. Yet another reason to use npm!
