### ISSUE TITLE
Add uatp support

### ISSUE THREAD

**Issue by rajat-explorer** [bendrucker/creditcards-types#21]
Please add Uatp card type

**Comment by bendrucker** [comment]
Happy to consider new card types with documentation

**Comment by rajat-explorer** [comment]
Though could not find official docs but here is a link to a reliablr specification

https://www.paypalobjects.com/webstatic/en_US/developer/docs/pdf/ppspec_uatpauth.pdf

Basic params are as below

Card number 15 digits
Grouped as 4,5 and 6 digits
No card cvc

**Comment by bendrucker** [comment]
That would work as a source. Where in that doc does it specify card formatting?

**Comment by rajat-explorer** [comment]
I suppose the following will help
{
  type: 'uatp',
  patterns: [1],
  format: /(\d{1,4})(\d{1,5})?(\d{1,6})?/,
  length: [15],
  cvcLength: [0],
  luhn: true
 }
Source: https://github.com/stripe/jquery.payment/issues/205

**Comment by bendrucker** [comment]
That's not an acceptable source. In order to avoid huge range overlaps I've relied on card issuer documentation. Without that I am not going to proceed.
