### ISSUE TITLE
Invalid/incomplete MasterCard 2-series BIN match

### ISSUE THREAD

**Issue by smrobinson** [bendrucker/creditcards-types#23]
I believe the pattern match for 2-series MasterCard BIN is incorrect. The range is '222100' - '272000' (per https://www.mastercard.us/content/dam/mccom/en-us/documents/partner-vendor-2-series-BIN-impact-checklist-aug-2016.pdf) which to me means the 2-series MC BIN cannot be properly recognized until the 4th digit.

Does MC actually own the entire 2-series BIN numbers? I cannot find a definitive statement about this but perhaps I've missed something.

**Comment by bendrucker** [comment]
That's reflected in the exact pattern but not the eager pattern:

https://github.com/bendrucker/creditcards-types/blob/master/src/types.js#L30-L31

The eager pattern is designed to match against a single card type as early as possible. No other issuer has any cards in the 2 range right now so a 2 does guarantee it's a MasterCard.

**Comment by smrobinson** [comment]
Shouldn't a BIN number like 272300, which is out of the range, fail the exact pattern match? For example, isCardValid returns true for 2723000048400016 and 2754444444444446 but they aren't valid since 2723 and 2754 are outside the range, right?

While I understand that only MC BINs start with '2' currently, isn't it safer, more "future proof", to make the eager pattern require 4 digits so the eager pattern does not say '28' or '2723' start a MC when in future another card is assigned a BIN outside the 2221 - 2720 range?

NB: I have a typo in my original note. The end of the range is '272099'.

**Comment by bendrucker** [comment]
Eager patterns are intended for UI hints, not to be exact. If you're interested in submitting a PR to tighten up the range and add relevant tests I'd be happy to review.
