### ISSUE TITLE
Wrong credit card type

### ISSUE THREAD

**Issue by yuxiaomin** [bendrucker/creditcards-types#28]
From https://en.wikipedia.org/wiki/Payment_card_number  we can know that the card number start from 6011 is discover credit card, eg  6011 1111 1111 1117

the result detected by creditcards-types is "Maestro". I found that in your code the number started from 60111 is judged as "Maestro", but looks like this is not correct.

**Comment by yuxiaomin** [comment]
There is an issue discussing this. sorry about that. I closed this issue.

**Comment by bendrucker** [comment]
Here's an up to date Discover doc (2/20/2017). I'd eventually like to archive these in this repo for safe keeping but haven't gotten around:

https://www.discovernetwork.com/downloads/IPP_VAR_Compliance.pdf

You'll see that Cybersource's test number is not in the official range so you can safely ignore the false result. I know this is a bit of a pain for end users but there's not much I can do about the common processor trend of using semi-valid card numbers for testing.
