### ISSUE TITLE
Add credit card type: Elo and Hipercard

### ISSUE THREAD

**Issue by vendramini** [bendrucker/creditcards-types#32]
Hi, could u add the Elo and Hipercard type? They are very common in Brazil. Thanks!

https://pastebin.com/duVq0tUv

**Comment by bendrucker** [comment]
See past issues, happy to review a PR but I don't take issues for uncommon card types.

**Comment by vendramini** [comment]
Yep, u r correctly, I apologize for this issue.

**Comment by bendrucker** [comment]
That's ok, no one's done it so far because no one's tracked down official docs. To date I've been able to make all the regular expressions non-overlapping. These cards with very broad/undocumented ranges might require some internal changes.

**Comment by vendramini** [comment]
Searching on brazilian forums I found that this companies doesn't answer with official docs, that's the reason some people did a compilation on pastebin sharing the currently mostly-accepted solution. Sad.

Thanks for your attention.
