### ISSUE TITLE
Can I create  pull request with a Brazilian creadit card?

### ISSUE THREAD

**Issue by jairorudas** [bendrucker/creditcards-types#34]
Hi, I'm using this repo in my job. But I need validate a local (brazilian) card. 
Can I create  pull request with a Brazilian creadit card?
Thanks, and sorry if I don't wrote fine.

**Comment by bendrucker** [comment]
Hi, you can totally add one! That's the best way to discuss the changes even if we decide against merging. I've been able to keep the ranges mutually exclusive, that might be a sticking point.
