### ISSUE TITLE
Elo Credit Card

### ISSUE THREAD

**Issue by jairorudas** [bendrucker/creditcards-types#36]
Hi Ben!

we need to add a new credit card, it's a Brazilian ELO. I talked to you a long time ago. Can you help us?
Here is the code which I've developed it.

``` exports.elo = new Type('Elo', {
 pattern: /^(4[035]|5[0]|6[235])(6[7263]|9[90]|1[2416]|7[736]|8[9]|0[04579]|5[0])([0-9])([0-9])\d{10}$/,
 eagerPattern: /^(4[035]|5[0]|6[235])(6[7263]|9[90]|1[2416]|7[736]|8[9]|0[04579]|5[0])([0-9])([0-9])/,
 groupPattern: group19
}) ```

**Comment by bendrucker** [comment]
Hey I haven’t had a chance to merge your PR yet, will get back to you soon
