### ISSUE TITLE
TypeScript query

### ISSUE THREAD

**Issue by rhys-vdw** [bendrucker/creditcards-types#38]
Hi @bendrucker, how are you doing?

We're using your library in a primarily TypeScript codebase. Is there any appetite for porting this repo to TypeScript?

Otherwise I'll consider opening a PR at DefinitelyTyped.

**Comment by bendrucker** [comment]
> Is there any appetite for porting this repo to TypeScript?

Definitely not. I'll take a PR for typings here too. Not into TS myself but I have noticed editors/plugins (esp VS Code) using a variety of signals (TS, JSDoc, probably flow too) to annotate code and provide completion.

**Comment by rhys-vdw** [comment]
> Definitely not.

> I'll take a PR for typings here too.
Sure. My only hesitation would be adding a burden on you (or other maintainers) who may not be well positioned to update the type files with subsequent releases. I wouldn't want to permit the types to get out of sync, or to add friction to the release flow. If you're happy with that I can PR here, otherwise i'll just create a DefinitelyTyped repo that can be maintained in parallel.

**Comment by bendrucker** [comment]
I hear ya. I’m accepting the maintence cost with this project’s simplicity in mind.

**Comment by rhys-vdw** [comment]
I've added it to the UsabilityHub bug issue tracker... Happy for someone to beat me to it.
