### ISSUE TITLE
Not able to recognize credit cards with number length less than 16 (maestro)

### ISSUE THREAD

**Issue by swapneshk** [bendrucker/creditcards-types#4]
In the demo, I am trying Maestro demo number - 5018 0000 0009, which is a valid number, but Its showing invalid and unknown.

12 digit card number is mentioned at - http://jquerycreditcardvalidator.com/ under (try one of these) also I checked the same at http://www.freeformatter.com/credit-card-number-generator-validator.html and its validating . I also tried at http://formvalidation.io/validators/creditCard/ and working.

maestro 12 digit number is also available at  - http://en.wikipedia.org/wiki/Bank_card_number

**Comment by bendrucker** [comment]
Secondhand sources don't count, but that Wikipedia article is great. Not sure how I missed that Maestro is 12-19 since I've used it many times before.

**Comment by bendrucker** [comment]
See the passing test. Can't reproduce. Please be sure you have the latest version.

**Comment by swapneshk** [comment]
Ok, I will test this with latest version..thx for the prompt support.
