### ISSUE TITLE
Troy Card Support

### ISSUE THREAD

**Issue by fatihsari** [bendrucker/creditcards-types#73]
Hello @bendrucker,

Congrats for this beautiful module.
How would you like to add Troy(Turkey CC Brand) in your module?

Can these help?
https://en.wikipedia.org/wiki/Troy_(card_scheme)
https://en.wikipedia.org/wiki/Payment_card_number

Have a nice coding!

**Comment by bendrucker** [comment]
Troy is already supported!

https://github.com/bendrucker/creditcards-types/blob/master/types/troy.js
